# Generated by Django 5.0.1 on 2024-01-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('family', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('modelbank', models.BooleanField(default=False)),
                (
                    'journey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='products.journey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'journey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='products.journey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('release_date', models.DateField()),
                (
                    'journey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='products.journey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SubFeature',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'feature',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='products.feature',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                (
                    'journey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='products.journey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ValueStream',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'journey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='products.journey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'journey',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='products.journey',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'journeys',
                    models.ManyToManyField(
                        through='products.Release', to='products.journey'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='products.version'
            ),
        ),
    ]
