# Generated by Django 5.0.1 on 2024-01-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='journey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='products.journey',
            ),
        ),
        migrations.AlterField(
            model_name='release',
            name='journey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='products.journey',
            ),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='products.version',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='journey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='products.journey',
            ),
        ),
        migrations.AlterField(
            model_name='valuestream',
            name='journey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='products.journey',
            ),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='journey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='products.journey',
            ),
        ),
        migrations.AlterField(
            model_name='version',
            name='journeys',
            field=models.ManyToManyField(
                blank=True, null=True, through='products.Release', to='products.journey'
            ),
        ),
    ]
