# Generated by Django 5.0.1 on 2024-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_alter_owner_journey_alter_release_journey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='journey',
        ),
        migrations.AlterField(
            model_name='version',
            name='journeys',
            field=models.ManyToManyField(
                blank=True, through='products.Release', to='products.journey'
            ),
        ),
        migrations.AddField(
            model_name='vendor',
            name='journey',
            field=models.ManyToManyField(null=True, to='products.journey'),
        ),
    ]
