# Generated by Django 5.0.1 on 2024-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_remove_vendor_journey_alter_version_journeys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='journey',
            field=models.ManyToManyField(blank=True, to='products.journey'),
        ),
    ]
