# Generated by Django 5.0.1 on 2024-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_alter_vendor_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='team',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='valuestream',
            name='journey',
        ),
        migrations.AddField(
            model_name='owner',
            name='journey',
            field=models.ManyToManyField(blank=True, to='products.journey'),
        ),
        migrations.AddField(
            model_name='team',
            name='journey',
            field=models.ManyToManyField(blank=True, to='products.journey'),
        ),
        migrations.AddField(
            model_name='valuestream',
            name='journey',
            field=models.ManyToManyField(blank=True, to='products.journey'),
        ),
    ]
