# Generated by Django 5.0.1 on 2024-01-22 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_rename_owner_assignee_project_delete_valuestream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignee',
            old_name='journey',
            new_name='journeys',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='journey',
            new_name='journeys',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='journey',
            new_name='journeys',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='journey',
            new_name='journeys',
        ),
    ]
